import type { Metadata } from "next";
import { Sora } from "next/font/google";
import "./globals.css";
import QueryProviders from "../providers/QueryProvider";

const sora = Sora({
    variable: "--font-sora",
    subsets: ["latin"],
});

export const metadata: Metadata = {
    title: "Vehiqo - Vehicle Rental System",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <body className={`${sora.variable} antialiased`}>
                <QueryProviders>{children}</QueryProviders>
            </body>
        </html>
    );
}
