import type { Metadata } from "next";
import { Sora, Geist } from "next/font/google";
import "./globals.css";
import QueryProviders from "../providers/QueryProvider";
import { Toaster } from "sonner";
import { cn } from "@/lib/utils";

const geist = Geist({ subsets: ["latin"], variable: "--font-sans" });

const sora = Sora({
    variable: "--font-sora",
    subsets: ["latin"],
});

export const metadata: Metadata = {
    title: "Vehiqo | Vehicle Rental System",
    description: "Generated by create next app",
    icons: {
        icon: "/l.svg",
        shortcut: "/l.svg",
        apple: "/l.svg",
    },
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en" className={cn("font-sans", geist.variable)}>
            <body className={`${sora.className} antialiased`}>
                <QueryProviders>{children}</QueryProviders>
                <Toaster richColors />
            </body>
        </html>
    );
}
